[package]
name = "trashcan"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["user"] }
chrono = "0.4.41"
clap = "4.5.38"
users = "0.11.0"
thiserror = "2.0.12"
log = "0.4.27"
uuid = { version = "1.16.0", features = ["v4"] }

