[package]
name = "trashcan"
version = "1.1.1"
edition = "2024"

[dependencies]
clap = "4.5.38"
users = "0.11.0"
thiserror = "2.0.12"
log = "0.4.27"
uuid = { version = "1.16.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.13"
