[package]
name = "trashcan"
version = "1.2.6"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
humansize = "2.1.3"
owo-colors = "4.2.2"
users = "0.11.0"
chrono = "0.4.41"
dialoguer = "0.11.0"

[dev-dependencies]