[package]
name = "trashcan"
version = "1.1.2"
edition = "2024"

[dependencies]
clap = "4.5.38"
clap_complete = "4.5.50"
users = "0.11.0"
uuid = { version = "1.16.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.13"
