services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins:docker
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always

volumes:
  jenkins_home:
    name: jenkins_home
